import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import {
  canonicalHeaders,
  notFoundHeaders,
  assetHeaders,
} from './security.mjs';
import { serviceWorkerSource } from './service-worker.mjs';
import { collectPublicAssets, isBuildArtifact } from './static-assets.mjs';

const source = path.resolve('dist/client');
const output = path.resolve('dist/workers');
const headers = JSON.parse(
  await readFile('dist/security-headers.json', 'utf8'),
);
// Validate before replacing the last successful package. Framework-generated
// deployment controls are excluded, while unexpected private files still fail.
const { files: publicFiles, excluded } = await collectPublicAssets(source);
await rm(output, { recursive: true, force: true });
await cp(source, output, {
  recursive: true,
  filter: (file) => !isBuildArtifact(path.relative(source, file)),
});
if (excluded.length)
  console.log(
    `Excluded build metadata from Workers assets: ${excluded.join(', ')}`,
  );

// Workers Static Assets limits each _headers line to 2,000 characters. Keep the full hashed
// document policy before all resources, and frame-ancestors in an HTTP header
// because browsers ignore that directive in a CSP meta element.
const documentPolicy = headers['Content-Security-Policy']
  .split('; ')
  .filter((directive) => !directive.startsWith('frame-ancestors '))
  .join('; ');
const escapedPolicy = documentPolicy
  .replaceAll('&', '&amp;')
  .replaceAll('"', '&quot;');
for (const file of ['index.html', '404.html']) {
  const filePath = path.join(output, file);
  const html = await readFile(filePath, 'utf8');
  if (
    !html.includes('<head>') ||
    /http-equiv="Content-Security-Policy"/i.test(html)
  )
    throw new Error(`Expected one unmodified document head: ${file}`);
  await writeFile(
    filePath,
    html.replace(
      /(<head>)(<meta charset=[^>]+>)?/i,
      (_, head, charset = '') =>
        `${head}${charset}<meta http-equiv="Content-Security-Policy" content="${escapedPolicy}">`,
    ),
  );
}

const rules = [
  [
    '/*',
    {
      ...headers,
      'Content-Security-Policy':
        "frame-ancestors 'none'; base-uri 'none'; object-src 'none'; form-action 'none'; script-src-attr 'none'",
    },
  ],
  ['/', canonicalHeaders],
  ['/404', notFoundHeaders],
];

// Use one cache policy per asset: Workers Static Assets joins overlapping header values.
rules.push(['/_next/static/*', assetHeaders('/_next/static/asset.js')]);
for (const file of publicFiles.filter(
  (file) => !file.startsWith('_next/static/'),
)) {
  const pathHeaders = assetHeaders(`/${file}`);
  if (Object.keys(pathHeaders).length) rules.push([`/${file}`, pathHeaders]);
}
if (rules.length > 100)
  throw new Error('Workers Static Assets allows at most 100 header rules.');
const workerHeaders =
  '# Generated by build:workers. Do not edit this output.\n' +
  rules
    .map(
      ([pattern, values]) =>
        `${pattern}\n${Object.entries(values)
          .map(([name, value]) => `  ${name}: ${value}`)
          .join('\n')}`,
    )
    .join('\n\n') +
  '\n';
if (workerHeaders.split('\n').some((line) => line.length > 2000))
  throw new Error(
    'Workers Static Assets allows at most 2,000 characters per _headers line.',
  );
await writeFile(path.join(output, '_headers'), workerHeaders);

// Include the Workers Static Assets policy in the version, but never precache _headers: Workers Static Assets
// consumes it as deployment configuration and does not serve it as an asset.
const filesToCache = publicFiles.filter(
  (file) => !file.endsWith('sw.js') && file !== '404.html',
);
const hash = createHash('sha256').update(workerHeaders);
for (const file of filesToCache) {
  hash.update(file);
  hash.update(await readFile(path.join(output, file)));
}
const version = hash.digest('hex').slice(0, 12);
const urls = [
  '/',
  ...filesToCache
    .filter((file) => file !== 'index.html')
    .map((file) => `/${file}`),
];
const worker = serviceWorkerSource(urls, version);
await writeFile(path.join(output, 'sw.js'), worker);
await writeFile(path.join(output, 'standalone-sw.js'), worker);
// Wrangler's standard generated-config pointer makes a plain `wrangler deploy`
// after this build select the finished static package, including after Vite's
// Cloudflare plugin has written its own pointer to intermediate client output.
const deployDirectory = path.resolve('.wrangler/deploy');
const deployConfig = path.resolve('deploy/cloudflare-workers/wrangler.jsonc');
await mkdir(deployDirectory, { recursive: true });
await writeFile(
  path.join(deployDirectory, 'config.json'),
  JSON.stringify(
    {
      configPath: path
        .relative(deployDirectory, deployConfig)
        .split(path.sep)
        .join('/'),
    },
    null,
    2,
  ) + '\n',
);
console.log(
  `Workers Static Assets: dist/workers, ${rules.length} header rules, ${urls.length} offline assets, version ${version}. Static assets only; no server entry point.`,
);
